[package]
name = "bf_compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
aho-corasick = "1.1.3"
clap = { version = "4.5.46", features = ["derive"] }
object = { version = "0.30.0", features = ["write"] }
dynasmrt = "3.2.1"
lazy_static = "1.5.0"
